### ISSUE TITLE
spray-client: Error on a server restart

### ISSUE THREAD

**Issue by ddelautre** [spray/spray#1000]
When doing tests that start a server before each test and stop it after each test, I have an error on the second test that do a request with spray-client.

It can be: Premature connection close (the server doesn't appear to support request pipelining)
or: ErrorClosed(Connection reset by peer)
and I think that I have already seen: Unexpected connection termination

I have shared a project on github that can reproduce the problem (it throws the ErrorClosed(Connection reset by peer), I had the Premature connection close when testing with a server that did not use spray-can) here: https://github.com/ddelautre/spray-client-problem

This is what I have when running the Main app:

```
Test 1
[INFO] [01/27/2015 22:35:03.506] [server-akka.actor.default-dispatcher-2] [akka://server/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:8080
test
[INFO] [01/27/2015 22:35:03.651] [server-akka.actor.default-dispatcher-2] [akka://server/user/IO-HTTP/listener-0] Unbound from localhost/127.0.0.1:8080
Test 2
[INFO] [01/27/2015 22:35:03.656] [server-akka.actor.default-dispatcher-4] [akka://server/user/IO-HTTP/listener-1] Bound to localhost/127.0.0.1:8080
[INFO] [01/27/2015 22:35:03.661] [server-akka.actor.default-dispatcher-7] [akka://server/system/IO-TCP/selectors/$a/1] Message [akka.io.SelectionHandler$ChannelReadable$] from Actor[akka://server/deadLetters] to Actor[akka://server/system/IO-TCP/selectors/$a/1#521667337] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Exception in thread "main" spray.can.Http$ConnectionException: ErrorClosed(Connection reset by peer)
	at spray.can.client.HttpHostConnectionSlot.reportDisconnection(HttpHostConnectionSlot.scala:228)
	at spray.can.client.HttpHostConnectionSlot$$anonfun$connected$1.applyOrElse(HttpHostConnectionSlot.scala:161)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at spray.can.client.HttpHostConnectionSlot.aroundReceive(HttpHostConnectionSlot.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[WARN] [01/27/2015 22:35:03.664] [client-akka.actor.default-dispatcher-6] [akka://client/user/IO-HTTP/host-connector-0/0] ErrorClosed(Connection reset by peer) in response to POST request to /test with no retries left, dispatching error...
[INFO] [01/27/2015 22:35:03.876] [server-akka.actor.default-dispatcher-3] [akka://server/user/IO-HTTP/listener-0/0] Message [spray.io.TickGenerator$Tick$] from Actor[akka://server/deadLetters] to Actor[akka://server/user/IO-HTTP/listener-0/0#445459404] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

And this is what I have if I put a sleep of 10ms after the first stop (no error):

```
Test 1
[INFO] [01/27/2015 22:53:00.860] [server-akka.actor.default-dispatcher-2] [akka://server/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:8080
test
[INFO] [01/27/2015 22:53:01.012] [server-akka.actor.default-dispatcher-2] [akka://server/user/IO-HTTP/listener-0] Unbound from localhost/127.0.0.1:8080
Test 2
[INFO] [01/27/2015 22:53:01.029] [server-akka.actor.default-dispatcher-2] [akka://server/user/IO-HTTP/listener-1] Bound to localhost/127.0.0.1:8080
test
Test 3
[INFO] [01/27/2015 22:53:01.035] [server-akka.actor.default-dispatcher-7] [akka://server/user/IO-HTTP/listener-1] Unbound from localhost/127.0.0.1:8080
[INFO] [01/27/2015 22:53:01.040] [server-akka.actor.default-dispatcher-5] [akka://server/user/IO-HTTP/listener-2] Bound to localhost/127.0.0.1:8080
test
[INFO] [01/27/2015 22:53:01.045] [server-akka.actor.default-dispatcher-7] [akka://server/user/IO-HTTP/listener-2] Unbound from localhost/127.0.0.1:8080
[INFO] [01/27/2015 22:53:01.230] [server-akka.actor.default-dispatcher-8] [akka://server/user/IO-HTTP/listener-0/0] Message [spray.io.TickGenerator$Tick$] from Actor[akka://server/deadLetters] to Actor[akka://server/user/IO-HTTP/listener-0/0#1164793745] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [01/27/2015 22:53:01.298] [server-akka.actor.default-dispatcher-8] [akka://server/user/IO-HTTP/listener-1/0] Message [spray.io.TickGenerator$Tick$] from Actor[akka://server/deadLetters] to Actor[akka://server/user/IO-HTTP/listener-1/0#1378928712] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [01/27/2015 22:53:01.307] [server-akka.actor.default-dispatcher-8] [akka://server/user/IO-HTTP/listener-2/0] Message [spray.io.TickGenerator$Tick$] from Actor[akka://server/deadLetters] to Actor[akka://server/user/IO-HTTP/listener-2/0#-1270148421] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by jrudolph** [comment]
I'd say this is an expected race condition: spray-can has a pool of persistent connections on the client side. The first test creates a persistent connection that is idle after the first request completed. By shutting down the server, you forcibly shut down those idle connections which isn't happening immediately but needs to travel over the wire (i.e. the TCP FIN/RST packet). Before the connection closing is detected on the client side you run a new POST request onto this terminating connection which then fails. Because a POST request isn't idempotent there is no way to retry it automatically.

If it's just for the test, use `IO(Http) ! CloseAll` to shutdown all client connections before running another test (make sure you don't run tests in parallel in that case as it will close down connections globally for that ActorSystem).

For the real world case, this is still a common enough race condition (server closing the connection vs client sending a POST request). We could add a flag not to use a persistent connection for non-idempotent requests. This still wouldn't fix it but would maybe make it less likely.

**Comment by sirthias** [comment]
I don't consider this a bug.
After all the server forcibly closing the connection should result in error messages on the client.
Not using keep-alive connections for non-idempotent requests, just for reducing the likelihood of errors in case the server shuts down, doesn't appear to be a good trade-off in my view.

**Comment by hmpatel** [comment]
What about the case where the idle-timeout is set to some seconds. When spray tries to close such idle connections on the timeout, it would still be the same race condition situation (server closing the connection vs client sending a POST request) ? 

We do see such Connection Reset very heavily into our system where we have the idleTimeout set to 60 seconds.

**Comment by jrudolph** [comment]
@hmpatel Is the question if the connection idle timeout interferes with new or ongoing client connections? Or is it about the host connector idle timeout?

How exactly do you use spray?

**Comment by hmpatel** [comment]
Is the question if the connection idle timeout interferes with new or ongoing client connections? Or is it about the host connector idle timeout?
Yes that's correct. We are using the host level API and have not set idle-timeout explicitly so essentially the default idle-timeout of 30 seconds is getting applied in this case.  Here is our Spray configuration :
spray.can {
  host-connector {
    max-connections = 500
    max-retries = 3
  }
  client {
    request-timeout = 40 s
    connecting-timeout = 2 s
  }
  manager-dispatcher = "spray-dispatcher"
  settings-group-dispatcher = "spray-dispatcher"
  host-connector-dispatcher = "spray-dispatcher"
  listener-dispatcher = "spray-dispatcher"
  connection-dispatcher = "spray-dispatcher"
}

We are experiencing lot of connection reset errors in production:
loggerName="s.can.client.HttpHostConnectionSlot" ErrorClosed(Connection reset by peer) in response to POST request to /api/v1/blah/blah with no retries left, dispatching error... 

How exactly do you use spray? 
We use the Host Level API since we connect to multiple hosts and want to maintain different connection pools, timeouts etc for each host. 

Furthermore, from the TCP capture we noticed that the client is resetting the connecting exactly after 120 seconds in all the cases. In other words, from the TCP stream, we see there is series of packets exchanged and then there is 120 seconds of  pause with no activity and immediately followed by the RST packet later.

**Comment by hmpatel** [comment]
@jrudolph - On your comment - "We could add a flag not to use a persistent connection for non-idempotent requests." Is this feature supported in Spray?

**Comment by discordianfish** [comment]
I just opened https://github.com/spray/spray/issues/1081 which might be related. I don't know how the test servers work, but if it set `Connection: close` it should be valid to close them on the server side.
