### ISSUE TITLE
HTTP Client doesn't support "//" at the beginning or a URL path

### ISSUE THREAD

**Issue by damienlevin** [spray/spray#1019]
Hi,

I'm running the following code and spray doesn't seem to like the "//"  at the beginning of a URL path.
Most browsers as well as curl don't seem to have any issue with this kind of URLs.

In addition to that, the error message is wrong, the URI I'm passing definitely has an authority

curl -i "http://apps.testinsane.com//rte/random"
HTTP/1.1 205 Reset Content

```
package test

import akka.actor._
import scala.concurrent._
import spray.http._
import spray.client.pipelining._

object Test extends App {

  import scala.concurrent.ExecutionContext.Implicits.global
  implicit val system = ActorSystem("Test")

  def request: HttpRequest ⇒ Future[HttpResponse] = sendReceive

  request(Get(Uri("http://apps.testinsane.com//rte/random"))) map {
    resp ⇒ 
    println("OK")
  } recover {
    case e: Exception ⇒
      e.printStackTrace
  }
}
```

```
spray.http.IllegalUriException: The path of an URI without authority must not begin with "//"
	at spray.http.Uri$.fail(Uri.scala:765)
	at spray.http.Uri$.verifyPath(Uri.scala:731)
	at spray.http.Uri$.apply(Uri.scala:241)
	at spray.http.Uri.toRelative(Uri.scala:180)
	at spray.can.HttpManager$$anonfun$receive$1.applyOrElse(HttpManager.scala:48)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at spray.can.HttpManager.aroundReceive(HttpManager.scala:29)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Thanks

**Comment by sirthias** [comment]
What spray version are you reporting this against?

**Comment by damienlevin** [comment]
Sorry I forgot to mention, I'm using 1.3.1.

**Comment by sirthias** [comment]
Ok, thanks.
The problem is interesting. It lies in the `toRelative` URI transformation we do when forwarding the request to the correct `HttpHostConnector`. Paths starting with a double-slash are not legal without an authority part, so we cannot actually strip off the authority, i.e. convert into a relative URI.
This means that, for these kinds of URIs, we need to add a `Host` and *keep* the URI in absolute form.

I just confirmed that `curl` actually does things wrong here. If you do a `curl -I http://spray.io//foo` it will send this request:

```
HEAD //foo HTTP/1.1
User-Agent: curl/7.30.0
Host: spray.io
Accept: */*
```

which is incorrect, because `//foo` is actually an absolute request without scheme to the root of host `foo`.

**Comment by sirthias** [comment]
I do need to correct my comment from above here.
Curl does in fact do things right and we parse request targets incorrectly.
See https://github.com/akka/akka/issues/17057 for more info.

**Comment by damienlevin** [comment]
Great news, thanks Mathias !
