### ISSUE TITLE
`HostConnectorSetup` doesn't handle IPv6 addresses well

### ISSUE THREAD

**Issue by nathanalderson** [spray/spray#1062]
`spray.can.Http.HostConnectorSetup` takes a `host: String` as its first parameter and a `port: Int` as its second.  However, if "host" is an IPv6 address, it must be surrounded by square brackets to avoid a `spray.http.IllegalUriException`.  This seems unnecessary since host and port are specified separately, and it puts an extra burden on my code to figure out which type of address I have in order to wrap the IPv6 addresses. It is easy to reproduce:

```
import akka.io.IO
import scala.concurrent.Await
import akka.actor.ActorSystem
import spray.can.Http
import akka.pattern.ask
import scala.concurrent.duration._
import akka.util.Timeout
implicit val timeout = Timeout(1 second)
import spray.can.Http
import spray.http._
import HttpMethods._

Await.result((IO(Http)(ActorSystem()) ? Http.HostConnectorSetup("::1", 8080)).mapTo[Http.HostConnectorInfo], 1 second)
```

Pasting this into a repl yields:

```
[default-akka.actor.default-dispatcher-3] ERROR akka.actor.OneForOneStrategy - Illegal URI host, unexpected character ':' at position 0: 
::1
^

akka.actor.ActorInitializationException: exception during creation
    at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
    at akka.actor.ActorCell.create(ActorCell.scala:596)
    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: spray.http.IllegalUriException: Illegal URI host, unexpected character ':' at position 0: 
::1
^

    at spray.http.Uri$.fail(Uri.scala:765)
    at spray.http.parser.UriParser.complete(UriParser.scala:429)
    at spray.http.Uri$Host$.apply(Uri.scala:373)
    at spray.can.client.HttpHostConnector.<init>(HttpHostConnector.scala:40)
    at spray.can.HttpManager$$anonfun$4.apply(HttpManager.scala:199)
    at spray.can.HttpManager$$anonfun$4.apply(HttpManager.scala:199)
    at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:340)
    at akka.actor.Props.newActor(Props.scala:249)
    at akka.actor.ActorCell.newActor(ActorCell.scala:552)
    at akka.actor.ActorCell.create(ActorCell.scala:578)
    ... 9 more
```

If we add brackets, it works fine:

```
val hci = Await.result((IO(Http)(ActorSystem()) ? Http.HostConnectorSetup("[::1]", 8080)).mapTo[Http.HostConnectorInfo], 1 second)
Await.result((hci.hostConnector ? HttpRequest(GET, Uri("/"))).mapTo[HttpResponse], 1 second)
```

yields

```
res1: spray.http.HttpResponse =
HttpResponse(200 OK,HttpEntity(text/html,<!doctype html>
...
```

This is with version 1.3.3.

**Comment by nathanalderson** [comment]
Closing as old
