### ISSUE TITLE
spray run on spark show java.lang.NoSuchMethodError: akka.actor.Props$.apply

### ISSUE THREAD

**Issue by cookeem** [spray/spray#1079]
I run the spray example simple-http-server on sbt is fine, but when I copy the spray jars to classpath and run on spark-submit (1.4.1 pre-built version), it always show java.lang.NoSuchMethodError: akka.actor.Props$.apply. I run spark-shell and input import akka.actor.Props.apply, it can find this method, I think it is the akka version problem so I check spark1.4.1 akka version, it's 2.3.4, and I use akka 2.3.4 to build the jar, anybody can help me?

my build.sbt file:

```
name := "simple-http-server"
version := "1.0"
scalaVersion := "2.10.5"
scalacOptions := Seq("-unchecked", "-deprecation", "-encoding", "utf8")
libraryDependencies ++= {
  val akkaV = "2.3.4"
  val sprayV = "1.3.2"
  Seq(
    "io.spray"            %%  "spray-json" % sprayV,
    "io.spray"            %%  "spray-can"     % sprayV,
    "io.spray"            %%  "spray-routing" % sprayV,
    //"io.spray"            %%  "spray-testkit" % sprayV  % "test",
    //"com.typesafe.akka"   %%  "akka-testkit"  % akkaV   % "test",
    "com.typesafe.akka"   %%  "akka-actor"    % akkaV
  )
}
```

full log like this:

```
java.lang.NoSuchMethodError: akka.actor.Props$.apply(Lscala/Function0;)Lakka/actor/Props;
	at spray.can.HttpExt.<init>(Http.scala:153)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
	at scala.util.Try$.apply(Try.scala:161)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
	at akka.actor.ExtensionKey.createExtension(Extension.scala:153)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:711)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.actor.ExtensionKey.apply(Extension.scala:149)
	at akka.io.IO$.apply(IO.scala:30)
```

**Comment by jrudolph** [comment]
This is likely to be a configuration issue where you run with an older Akka version than you are thinking you are. Try running `show externalDependencyClasspath` in sbt to find out which libraries are on your classpath.

The change that probably broke the compatibility in your case was [this](https://github.com/akka/akka/commit/33ebf24c0fec622869a5306312c3bac3ac889f68) and it predates Akka 2.3.0. 

In any case, this is not a spray bug, so it's likely to be akka or spark specific. If you cannot find out I suggest asking on the akka or spark mailing lists.

Closing for now...
