### ISSUE TITLE
Spray Json throw Error in Future onComplete method

### ISSUE THREAD

**Issue by littlejin** [spray/spray#1104]
here is my code,  I have already shorten unnecessary code

```
clientObject.query(_uri).onComplete {
        case Success(response) =>
        val resultJson = RecommResponseJsonParser.parse(response) 
        _sender ! HttpResponse(entity = HttpEntity(ContentTypes.`application/json`, resultJson))
          
        case Failure(e) => 
}
```

and this line ```val resultJson = RecommResponseJsonParser.parse(response) ``` cause exception like this

```
[error] java.lang.IllegalArgumentException: requirement failed
[error] 	at scala.Predef$.require(Predef.scala:207)
[error] 	at spray.json.BasicFormats$StringJsonFormat$.write(BasicFormats.scala:121)
[error] 	at spray.json.BasicFormats$StringJsonFormat$.write(BasicFormats.scala:119)
[error] 	at spray.json.ProductFormats$class.productElement2Field(ProductFormats.scala:45)
[error] 	at com.sina.recomm.util.json.RecommResponseJsonParser$MyJsonProtocol$.productElement2Field(RecommResponseJsonParser.scala:26)
[error] 	at spray.json.ProductFormatsInstances$$anon$10.write(ProductFormatsInstances.scala:286)
[error] 	at spray.json.ProductFormatsInstances$$anon$10.write(ProductFormatsInstances.scala:278)
[error] 	at com.sina.recomm.util.json.RecommResponseJsonParser$MyJsonProtocol$ProfileJsonFormat$.write(RecommResponseJsonParser.scala:35)
[error] 	at com.sina.recomm.util.json.RecommResponseJsonParser$MyJsonProtocol$ProfileJsonFormat$.write(RecommResponseJsonParser.scala:34)
[error] 	at spray.json.PimpedAny.toJson(package.scala:39)
[error] 	at spray.json.CollectionFormats$$anon$1$$anonfun$write$1.apply(CollectionFormats.scala:26)
[error] 	at spray.json.CollectionFormats$$anon$1$$anonfun$write$1.apply(CollectionFormats.scala:26)
[error] 	at scala.collection.immutable.List.map(List.scala:273)
[error] 	at spray.json.CollectionFormats$$anon$1.write(CollectionFormats.scala:26)
[error] 	at spray.json.CollectionFormats$$anon$1.write(CollectionFormats.scala:25)
[error] 	at spray.json.PimpedAny.toJson(package.scala:39)
[error] 	at com.sina.recomm.util.json.RecommResponseJsonParser$.parse(RecommResponseJsonParser.scala:65)
[error] 	at com.sina.recomm.client.ClientActor$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(ClientActor.scala:79)
[error] 	at com.sina.recomm.client.ClientActor$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(ClientActor.scala:59)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

here is how I defined my json protocol,

```
case class IMG(url: String, width: Int, height: Int)

case class Profile(url: String,
                   title: String,
                   summary: String,
                   categoryid: String,
                   ctime: String,
                   keywords: Vector[String],
                   imgs: Vector[IMG],
                   commentNum: Int,
                   likeNum: Int,
                   subChannel: String)

object RecommResponseJsonParser extends SLF4JLogging {

  object MyJsonProtocol extends DefaultJsonProtocol {

    implicit object IMGJsonFormat extends RootJsonFormat[IMG] {
      override def write(img: IMG): JsValue = jsonFormat3(IMG).write(img)

      override def read(value: JsValue): IMG = jsonFormat3(IMG).read(value)
    }

    implicit object ProfileJsonFormat extends RootJsonFormat[Profile] {
      override def write(obj: Profile): JsValue = jsonFormat10(Profile).write(obj)

      override def read(value: JsValue): Profile = jsonFormat10(Profile).read(value)
    }
  }

  def parse(response: RecommendationResponse): String = {
    import MyJsonProtocol._
    response.results.map {
      s =>
        val keywords = s.abstr.split(" ").tail.toVector
        val tags = s.tags.toVector
        val images = if (s.getImagesSize > 0) {
          s.images.map(img => IMG(img.getUrl, img.getWidth, img.getHeight)).toVector
        } else {
          Vector()
        }

        Profile(s.url,
          s.title,
          s.abstr,
          s.vertical_type,
          s.pubtime,
          if (tags.isEmpty) keywords else tags,
          images,
          s.comment_num,
          s.like_num,
          s.sub_channel)
    }.toList.toJson.prettyPrint
  }
}
```
Any idea how to solve this ?

**Comment by wjur** [comment]
The stacktrace points to BasicFormats.scala:121 which is in StringJsonFormat object:
<code>require(x ne null)</code>
It seems that one of the strings in the Profile instance is null and Spray can't convert it to Json.
If nulls are correct values for the string fields you could use Option[String] instead of String. If they're not then you have to look for the code that introduces nulls.

**Comment by littlejin** [comment]
Very Helpful @wjur , issue closed
