### ISSUE TITLE
routing: FileAndResourceDirectives.getFromResource keeps file open

### ISSUE THREAD

**Issue by rditerwich** [spray/spray#412]
The cause is this line:

val lastModified = url.openConnection().getLastModified

The file is kept open, which takes resources, but is particularly annoying in windows when updating web resource files while developing.

**Comment by OlegYch** [comment]
still seeing leeked file descriptors here 
at java.io.FileInputStream.<init>(FileInputStream.java:139)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.initializeHeaders(FileURLConnection.java:110)
    at sun.net.www.protocol.file.FileURLConnection.getHeaderField(FileURLConnection.java:146)
    at sun.net.www.protocol.jar.JarURLConnection.getHeaderField(JarURLConnection.java:228)
    at java.net.URLConnection.getHeaderFieldDate(URLConnection.java:654)
    at java.net.URLConnection.getLastModified(URLConnection.java:559)
    at spray.routing.directives.FileAndResourceDirectives$class.getFromResource(FileAndResourceDirectives.scala:126)
spray 1.3.3 jvm8u31 on windows, and oracle 8u72 on ubuntu

btw i have routes defined like runRoute(respondWithHeaders(){requestInstance {parameterMap {routes ~ getFromResource}}) and resource is accessed on every request instead of only if "routes" didn't match, so every request leaks a file handle, any reason for this?
